### ISSUE TITLE
First Link to the Developers Garden is not working

### ISSUE THREAD

**Issue by w1kke** [SeedVault/IP#1]
Hey,

small issue which I don't want to make a pull request for - the first link to the Developers Garden in this text passage is not working correctly:

Go to our Developers Garden to see all featured projects, pick one and fill out the Developer Interest Form. If you rather like to discuss ideas before rolling up your sleeves, please come visit our Discord channels for developers

**Comment by SEEDToken** [comment]
Hi @w1kke , thanks for letting us know! Fixed it just now. Gaby@seedtoken.io
